# Used for this repo!
# Code housekeeping (linting, typing, etc.) is performed pre-commit; could add it here, too.

image: python:3.9

pipelines:
  default:
    - step:
        name: Scan with Salus
        caches:
          - docker
        services:
          - docker
        script:
          - docker run --rm -t -v $(pwd):/home/repo coinbase/salus
    - step:
        name: Build and test
        caches:
          - pip
        script:
          - apt-get update && apt-get install -y git
          - pip install pipenv
          - pipenv install --dev
          - pipenv run python -m unittest discover
